/**
 * The learning loop's reports, as PURE functions of the validated records and the policy's one
 * threshold: records in, `path -> bytes` out. No file system, no clock, no tracker, no reference.
 *
 *   recurring.md         the same stage and asset pair on distinct items
 *   disagreements.md     the same kind of decision made two ways
 *   undecided.md         what runs could not decide
 *   dead-or-blocked.md   runs that failed, runs that stopped to ask, and why
 *   proposals.md/.json   the proposal list, keyed on subject and fact
 *
 * kit 3.4-1 · ADAPT: the four shapes are the general ones for any per-item workflow; the COLUMNS are
 * yours. Add one by reading another field of the record here; never by reading anything else.
 *
 * THE FAILURE IT EXISTS TO PREVENT. On day one, two of them. A report that reads anything but the
 * records (the tracker, the reference, the date) cannot be re-derived by `--check`, so nobody can
 * tell a stale report from a current one. And a rate printed over two records reads as a finding:
 * "100% of runs hit this" is two runs. Below `minimumSampleSize` a report prints its counts and
 * says the rate is withheld, with both numbers.
 *
 * AN EMPTY RECORDS DIRECTORY IS LEGAL. Every report then says so, in words, with its source named,
 * rather than printing an empty table that reads like "nothing recurs".
 *
 * INVOCATION. Imported by `index.ts` and `propose.ts`; never run. NEEDS. Nothing.
 */
import { createHash } from 'node:crypto'
import { EMITTER, RECORDS_DIR, REPORTS_DIR } from './paths.ts'
import { canonicalJson, liveEntries } from './record.ts'
import type { RunOutcome } from './record.ts'

export const byCodePoint = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0)

// Built from two source lines on purpose: the hooks recognise a build product by a line that names
// a generator AND forbids the edit, and no line of this emitter may read as one.
const BANNER =
  `GENERATED by ${EMITTER} (\`npm run outcomes\`) from the records under ${RECORDS_DIR} and nothing else. ` +
  'DO NOT EDIT BY HAND: a change belongs in a record, through its writer, or in the emitter; then re-run.'

/* ------------------------------------------------------------------------------- the proposals -- */

export interface ProposalEvidence {
  item: string
  /** The commit the record names, at which a cited source line is checked. Null when it pushed nothing. */
  commit: string | null
  cites: string[]
}

export interface Proposal {
  /** sha256 over the normalised subject and fact, first 16 hex digits. The filing step's label carries it. */
  key: string
  subject: string
  fact: string
  assets: string[]
  stages: string[]
  items: string[]
  evidence: ProposalEvidence[]
  /** Keys of the other proposals on the same subject, so contradictions are read together. */
  siblings: string[]
}

/** Case, Unicode form and spacing do not make a new proposal; any other rewording does. */
const normalised = (text: string): string => text.normalize('NFC').toLowerCase().replace(/\s+/g, ' ').trim()

export function proposalKey(subject: string, fact: string): string {
  return createHash('sha256').update(`${normalised(subject)}\n${normalised(fact)}`).digest('hex').slice(0, 16)
}

/**
 * One proposal per distinct (subject, fact) among the corrections the records still stand behind
 * whose asset is not `none`: something durable would have spared the next run, and this is what it
 * should say. A correction that was itself superseded or retracted proposes nothing.
 */
export function deriveProposals(records: RunOutcome[]): Proposal[] {
  const byKey = new Map<string, Proposal>()
  for (const record of records) {
    for (const entry of liveEntries(record)) {
      if (entry.asset === null || entry.stage === null || entry.asset === 'none') continue
      const key = proposalKey(entry.subject, entry.fact)
      let proposal = byKey.get(key)
      if (proposal === undefined) {
        proposal = { key, subject: entry.subject, fact: entry.fact, assets: [], stages: [], items: [], evidence: [], siblings: [] }
        byKey.set(key, proposal)
      }
      if (!proposal.assets.includes(entry.asset)) proposal.assets.push(entry.asset)
      if (!proposal.stages.includes(entry.stage)) proposal.stages.push(entry.stage)
      if (!proposal.items.includes(record.item)) proposal.items.push(record.item)
      proposal.evidence.push({ item: record.item, commit: record.commit, cites: entry.evidence })
    }
  }
  const proposals = [...byKey.values()].sort((a, b) => byCodePoint(a.key, b.key))
  for (const p of proposals) {
    p.assets.sort(byCodePoint)
    p.stages.sort(byCodePoint)
    p.items.sort(byCodePoint)
    p.evidence.sort((a, b) => byCodePoint(a.item, b.item))
    p.siblings = proposals
      .filter((q) => q.key !== p.key && normalised(q.subject) === normalised(p.subject))
      .map((q) => q.key)
  }
  return proposals
}

/* ---------------------------------------------------------------------------------- the pieces -- */

const cell = (text: string): string => text.replace(/\s+/g, ' ').replace(/\|/g, '\\|').trim()

function table(head: string[], rows: string[][]): string[] {
  return [
    `| ${head.join(' | ')} |`,
    `|${head.map(() => '---').join('|')}|`,
    ...rows.map((row) => `| ${row.map(cell).join(' | ')} |`),
  ]
}

/** `n of total`, and the percentage only when `total` reaches the declared minimum sample. */
export function share(n: number, total: number, minimum: number): string {
  if (total < minimum) return `${String(n)} of ${String(total)} (rate withheld: fewer than ${String(minimum)} records)`
  return `${String(n)} of ${String(total)} (${String(Math.round((n / total) * 100))}%)`
}

function page(title: string, records: RunOutcome[], intro: string, body: string[]): string {
  const lines = [`<!-- ${BANNER} -->`, '', `# ${title}`, '']
  if (records.length === 0) {
    lines.push(
      `Source: \`${RECORDS_DIR}\`, which holds no record yet. That is a legal state and this report is` +
        ' empty because of it, not because nothing was found: the first record a run writes fills it.',
    )
  } else {
    lines.push(`Source: the ${String(records.length)} record(s) under \`${RECORDS_DIR}\`, and nothing else.`, '', intro, '', ...body)
  }
  return `${lines.join('\n')}\n`
}

/* --------------------------------------------------------------------------------- the reports -- */

function recurring(records: RunOutcome[], minimum: number): string {
  const retracted = (record: RunOutcome): Set<string> =>
    new Set(record.corrections.map((c) => c.retracts).filter((id): id is string => id !== null))
  const pairs = new Map<string, Set<string>>()
  for (const record of records) {
    const withdrawn = retracted(record)
    for (const c of record.corrections) {
      if (withdrawn.has(c.id)) continue
      const pair = `${c.stage}\u0000${c.asset}`
      if (!pairs.has(pair)) pairs.set(pair, new Set())
      pairs.get(pair)!.add(record.item)
    }
  }
  const rows = [...pairs.entries()]
    .filter(([, items]) => items.size >= 2)
    .sort(([a], [b]) => byCodePoint(a, b))
    .map(([pair, items]) => {
      const [stage, asset] = pair.split('\u0000')
      return [stage, asset, share(items.size, records.length, minimum), [...items].sort(byCodePoint).join(', ')]
    })
  return page(
    'What recurs across runs',
    records,
    'A row is a stage and asset pair that corrections on at least two DISTINCT items share: the same' +
      ' stage keeps producing an error that the same kind of asset would absorb. A correction that a' +
      ' later one retracted is not counted. One item meeting a pair five times is one item.',
    rows.length === 0
      ? ['None: no stage and asset pair appears on two distinct items.']
      : table(['Stage', 'Asset', 'Items carrying it', 'Item ids'], rows),
  )
}

function disagreements(records: RunOutcome[]): string {
  const kinds = new Map<string, Map<string, string[]>>()
  for (const record of records) {
    for (const d of record.decisions) {
      if (!kinds.has(d.kind)) kinds.set(d.kind, new Map())
      const choices = kinds.get(d.kind)!
      if (!choices.has(d.choice)) choices.set(d.choice, [])
      if (!choices.get(d.choice)!.includes(record.item)) choices.get(d.choice)!.push(record.item)
    }
  }
  const rows: string[][] = []
  for (const kind of [...kinds.keys()].sort(byCodePoint)) {
    const choices = kinds.get(kind)!
    if (choices.size < 2) continue
    for (const choice of [...choices.keys()].sort(byCodePoint)) {
      rows.push([kind, choice, [...choices.get(choice)!].sort(byCodePoint).join(', ')])
    }
  }
  return page(
    'Where runs disagree',
    records,
    'A kind of decision appears here when runs made it at least two ways. Each way is a row, with the' +
      ' items that chose it; the reason each run gave is in its record.',
    rows.length === 0 ? ['None: every kind of decision recorded was made one way.'] : table(['Kind of decision', 'Choice', 'Item ids'], rows),
  )
}

function undecided(records: RunOutcome[]): string {
  const rows = records.flatMap((record) => record.undecided.map((u) => [record.item, record.status, u.question, u.why]))
  return page(
    'What runs could not decide',
    records,
    'Every question a run recorded as undecided, with why it could not settle it.',
    rows.length === 0 ? ['None: no record carries an undecided question.'] : table(['Item', 'Status', 'Question', 'Why undecided'], rows),
  )
}

function deadOrBlocked(records: RunOutcome[], minimum: number): string {
  const count = (status: string): number => records.filter((r) => r.status === status).length
  const failed = records.filter((r) => r.failure !== null).map((r) => [r.item, r.failure!.stage, r.failure!.reason])
  const blocked = records
    .filter((r) => r.intervention !== null)
    .map((r) => [r.item, r.intervention!.reasonCode, r.intervention!.detail])
  return page(
    'What looks dead or blocked',
    records,
    'A failed run ended without its work and asked nobody; a blocked run stopped to ask a person and' +
      ' is waiting. Both wrote a record, which is the only reason this page can exist.',
    [
      ...table(
        ['Terminal status', 'Records'],
        ['complete', 'failed', 'blocked'].map((status) => [status, share(count(status), records.length, minimum)]),
      ),
      '',
      '## Failed',
      '',
      ...(failed.length === 0 ? ['None.'] : table(['Item', 'Stage that failed', 'Reason'], failed)),
      '',
      '## Blocked',
      '',
      ...(blocked.length === 0 ? ['None.'] : table(['Item', 'Intervention reason code', 'Detail'], blocked)),
    ],
  )
}

function proposalsPage(records: RunOutcome[], proposals: Proposal[]): string {
  const rows = proposals.map((p) => [`\`${p.key}\``, p.subject, p.fact, p.assets.join(', '), p.items.join(', '), p.siblings.map((k) => `\`${k}\``).join(', ')])
  return page(
    'Proposals',
    records,
    'One row per distinct subject and fact among the corrections the records still stand behind whose' +
      ' asset is not `none`. The key is a hash of the subject and the fact, and the filing step' +
      ' (`npm run outcomes:propose`) carries it as a label, so rewording a title never files a second' +
      ' issue. Siblings are other proposals on the same subject: read them together. A program' +
      ' proposes; only a person promotes.',
    rows.length === 0 ? ['None: no live correction names an asset that would absorb it.'] : table(['Key', 'Subject', 'Fact', 'Asset', 'Item ids', 'Siblings'], rows),
  )
}

/** Every report, as repository-relative path -> bytes. `records` are validated and sorted by item. */
export function deriveReports(records: RunOutcome[], minimumSampleSize: number): Map<string, string> {
  const proposals = deriveProposals(records)
  const out = new Map<string, string>()
  out.set(`${REPORTS_DIR}recurring.md`, recurring(records, minimumSampleSize))
  out.set(`${REPORTS_DIR}disagreements.md`, disagreements(records))
  out.set(`${REPORTS_DIR}undecided.md`, undecided(records))
  out.set(`${REPORTS_DIR}dead-or-blocked.md`, deadOrBlocked(records, minimumSampleSize))
  out.set(`${REPORTS_DIR}proposals.md`, proposalsPage(records, proposals))
  out.set(
    `${REPORTS_DIR}proposals.json`,
    canonicalJson({
      '//': BANNER,
      source: RECORDS_DIR,
      records: records.length,
      note: records.length === 0 ? `${RECORDS_DIR} holds no record yet; that is legal, and the list is empty because of it.` : null,
      proposals,
    }),
  )
  return out
}
