/**
 * emit.ts — the worked example's emitter: node `X-EXAMPLE` of `../graph.ts`.
 *
 * EMITS. `summary.json` beside this file: the entries of `entries.json` counted by state, their
 * names sorted, and under `provenance` the stamp that says what the summary was built FROM
 * (`stampFor('X-EXAMPLE')`: a digest of each declared input group and of the generator source).
 *
 * THE FAILURE IT EXISTS TO PREVENT. None of its own: it exists to show the one thing every emitter
 * behind the staleness gate has to do, which is write its input digest into its own output. On day
 * one, this is what an emitter that skipped it would let through: its node reports UNSTAMPED for
 * ever, which the gate reports and never fails, so an edit to `entries.json` with no re-run is a
 * summary that describes a list that no longer exists, and nothing says so. Copy the shape of
 * `build()` below into your own emitter: compute the body, take the stamp LAST, serialise once.
 *
 * INVOCATION.
 *   npm run pipeline:example                                  write `summary.json`
 *   node tools/pipeline/example/emit.ts --check       re-derive in memory, byte-compare,
 *                                                             exit 1 on any difference, write nothing
 * The `--check` twin has no package script because `npm run pipeline:stale:check` is the gate over
 * this node; `npm run pipeline:selftest` runs the twin against a doctored copy while this
 * directory exists.
 *
 * NEEDS. Nothing outside this repository. Deterministic: keys and names sorted by code point, one
 * serialiser. The stamp's `generatedAtUtc` is the one field that is not a function of the inputs,
 * and `provenance.ts` makes it sticky: when the digests equal the ones already on disk the prior
 * value is carried forward, so two runs over an unchanged repository are byte-identical. There is
 * no root override variable because there is nothing to override: the root is derived from where
 * the file stands (`../provenance.ts`), so to run it against a fixture, copy `tools/`
 * under a temp directory and run the copy.
 *
 * kit 3.6-4 · ADAPT: delete this directory with the node; `../graph.ts` lists what goes with it.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { stampFor } from '../provenance.ts'

const NODE_ID = 'X-EXAMPLE'
const HERE = dirname(fileURLToPath(import.meta.url))
const INPUT = join(HERE, 'entries.json')
const OUTPUT = join(HERE, 'summary.json')

const byCodePoint = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0)

/** The one serialiser: keys sorted at every depth, two-space indent, one trailing newline. */
function canonical(value: unknown): string {
  const sort = (v: unknown): unknown => {
    if (Array.isArray(v)) return v.map(sort)
    if (v && typeof v === 'object') {
      const o = v as Record<string, unknown>
      return Object.fromEntries(
        Object.keys(o)
          .sort(byCodePoint)
          .map((k) => [k, sort(o[k])]),
      )
    }
    return v
  }
  return `${JSON.stringify(sort(value), null, 2)}\n`
}

function readEntries(): { name: string; state: string }[] {
  const doc = JSON.parse(readFileSync(INPUT, 'utf8')) as { entries?: unknown }
  if (!Array.isArray(doc.entries)) throw new Error(`${INPUT}: "entries" is not an array`)
  const seen = new Set<string>()
  return doc.entries.map((e, i) => {
    const { name, state } = (e ?? {}) as { name?: unknown; state?: unknown }
    if (typeof name !== 'string' || typeof state !== 'string') {
      throw new Error(`${INPUT}: entry ${i + 1} needs a string "name" and a string "state"`)
    }
    if (seen.has(name)) throw new Error(`${INPUT}: "${name}" is listed twice`)
    seen.add(name)
    return { name, state }
  })
}

/** The whole output document, as the bytes to write. The stamp is taken last. */
function build(): string {
  const entries = readEntries()
  const byState: Record<string, number> = {}
  for (const e of entries) byState[e.state] = (byState[e.state] ?? 0) + 1
  return canonical({
    describes: 'GENERATED by emit.ts beside this file from entries.json. Do not edit; run `npm run pipeline:example`.',
    total: entries.length,
    byState,
    names: entries.map((e) => e.name).sort(byCodePoint),
    provenance: stampFor(NODE_ID),
  })
}

const next = build()
const prior = existsSync(OUTPUT) ? readFileSync(OUTPUT, 'utf8') : null

if (process.argv.includes('--check')) {
  if (prior === next) {
    console.log('pipeline:example --check: summary.json is what emit.ts would write.')
  } else {
    console.error(
      prior === null
        ? 'pipeline:example --check: summary.json does not exist.'
        : 'pipeline:example --check: summary.json differs from what emit.ts would write now.',
    )
    console.error('  run: npm run pipeline:example   (and commit the result)')
    process.exit(1)
  }
} else if (prior === next) {
  console.log('pipeline:example: summary.json is already current; nothing written.')
} else {
  writeFileSync(OUTPUT, next)
  console.log('pipeline:example: wrote summary.json; commit it with the change that moved it.')
}
